[devshell]
packages = ["alejandra", "dprint"]

[[commands]]
package = "treefmt"
category = "formatter"

[[commands]]
name = "my-nixos-build"
category = "nixos"
command = "nixos-rebuild build --flake \".#$(hostname)\""

[[commands]]
name = "my-nixos-switch"
category = "nixos"
command = "nixos-rebuild switch --flake \".#$(hostname)\" --use-remote-sudo"
