name: CI

on:
  push:

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: sno2wman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check --impure
        env:
          NIXPKGS_ALLOW_UNFREE: 1
          NIXPKGS_ALLOW_INSECURE: 1
