name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  treefmt:
    name: treefmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: sno2wman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix develop --command bash -c "treefmt --fail-on-change"
